default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fintera_development
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>

test:
  <<: *default
  database: fintera_test
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  