# Solid Queue Recurring Tasks
# Migrated from Sidekiq Scheduler (config/schedule.yml)

default: &default
  send_overdue_payment_mail:
    class: CheckPaymentsOverdueJob
    queue: default
    schedule: every day at 8am
    description: "Send overdue payment reminders to users"

  update_overdue_interest:
    class: UpdateOverdueInterestJob
    queue: default
    schedule: every day at 12am
    description: "Update interest for overdue payments"

  generate_statistics_hourly:
    class: GenerateStatisticsJob
    queue: default
    args: ["last_hour"]
    schedule: every hour
    description: "Generate hourly statistics"

  generate_revenue_daily:
    class: GenerateRevenueJob
    queue: default
    schedule: every day at 1am
    description: "Generate daily revenue report"

  release_unpaid_reservation:
    class: ReleaseUnpaidReservationJob
    queue: default
    schedule: every day at 2am
    description: "Release unpaid reservations"

development:
  <<: *default

test:
  # Disable recurring tasks in test environment
  {}

production:
  <<: *default
  
  # Maintenance task to clear finished jobs
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
    description: "Clean up finished Solid Queue jobs"
