
send_overdue_payment_mail:
  cron: "0 8 * * *"   # Runs every day at 8:00 AM
  class: "CheckPaymentsOverdueJob"
  queue: default

update_overdue_interest_job:
  cron: "0 0 * * *"   # Runs every day at 12:00 AM
  class: "UpdateOverdueInterestJob"
  queue: default

generate_statistics_daily:
    cron: "0 0 * * *" # Runs every day at midnight
    class: GenerateStatisticsJob
    args:
      - Date.yesterday
    queue: default

 generate_revenue_daily:
    cron: "0 1 * * *" # Runs at the start of every hour
    class: GenerateRevenueJob