send_overdue_payment_mail:
  cron: "0 8 * * *"   # Runs every day at 8:00 AM
  class: "CheckPaymentsOverdueJob"
  queue: default
  description: "Send overdue payment reminders to users"

update_overdue_interest_job:
  cron: "0 0 * * *"   # Runs every day at 12:00 AM
  class: "UpdateOverdueInterestJob"
  queue: default
  description: "Update interest for overdue payments"

generate_statistics_hourly:
  cron: "0 * * * *"  # Runs every hour on the hour
  class: GenerateStatisticsJob
  args:
    - "last_hour"  # Adjust argument as necessary; for example, "last_hour" or another relevant value
  queue: default
  description: "Generate hourly statistics"

generate_revenue_daily:
  cron: "0 1 * * *" # Runs every day at 1:00 AM
  class: GenerateRevenueJob
  queue: default
  description: "Generate daily revenue report"