:concurrency: 5
:queues:
  - high
  - default
  - mailers
:redis:
  :url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379/0' %>
:namespace: fintera
:logfile: ./log/sidekiq.log
:pidfile: ./tmp/pids/sidekiq.pid
:daemon: false
:require: ./config/environment

# Optional: Specify environment
:environment: <%= ENV['RAILS_ENV'] || 'development' %>

# Optional: Schedule file for sidekiq-cron
:schedule_file: config/schedule.yml