# Solid Queue Configuration
# https://github.com/basecamp/solid_queue

default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      concurrency_maintenance_interval: 600
      recurring_schedule_file: config/recurring.yml

  workers:
    - queues: high
      threads: 3
      processes: 2
      polling_interval: 0.1
    - queues: default
      threads: 5
      processes: 3
      polling_interval: 1
    - queues: mailers
      threads: 2
      processes: 1
      polling_interval: 2

development:
  <<: *default
  workers:
    - queues: "*"
      threads: 3
      processes: 1
      polling_interval: 1

test:
  <<: *default
  dispatchers:
    - polling_interval: 10
      batch_size: 100
  workers:
    - queues: "*"
      threads: 1
      processes: 1
      polling_interval: 10

production:
  <<: *default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      concurrency_maintenance_interval: 300
      recurring_schedule_file: config/recurring.yml

  workers:
    - queues: high
      threads: 5
      processes: 3
      polling_interval: 0.1
    - queues: default
      threads: 10
      processes: 5
      polling_interval: 1
    - queues: mailers
      threads: 3
      processes: 2
      polling_interval: 2
