name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: fintera_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d fintera_test" --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:6
        ports:
          - 6379:6379

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.6
          bundler-cache: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev

      - name: Install gems
        run: bundle install --jobs 4 --retry 3

      - name: Prepare DB config
        run: |
          cp config/database.yml.ci config/database.yml || true
          echo "HOSTNAME=localhost" >> $GITHUB_ENV

      - name: Wait for Postgres
        run: until pg_isready -h localhost -p 5432 -U postgres; do sleep 1; done

      - name: Setup DB
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/fintera_test
        run: |
          bundle exec rails db:create db:schema:load

      - name: Run specs
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/fintera_test
          SENTRY_DSN: ""
          SENTRY_ENV: "test"
        run: bundle exec rspec --format documentation
